version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    hostname: zookeeper
    networks:
      elasticsearch-network:
        ipv4_address: 10.5.0.2
  kafka:
    image: confluentinc/cp-kafka:5.2.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.5.0.3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    hostname: kafka 
    networks:
      elasticsearch-network:
        ipv4_address: 10.5.0.3
  redis:
    image: "redis:alpine"
    depends_on:
      - kafka
    ports:
      - "6379:6379"
    networks:
      elasticsearch-network:
        ipv4_address: 10.5.0.4
  logstash:
    image: "docker.elastic.co/logstash/logstash:7.1.0"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
      - ./sample_csv:/tmp/sample_csv
      - ./connector:/tmp/connector
    links:
      - redis
      - elasticsearch
      - kafka
    ports:
      - "5656:5656"
    networks:
      elasticsearch-network:
        ipv4_address: 10.5.0.5
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.0"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    depends_on:
      - kafka
      - redis
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: 'elasticsearch'
    networks:
      elasticsearch-network:
        ipv4_address: 10.5.0.6
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.1.0"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      elasticsearch-network:
        ipv4_address: 10.5.0.7
networks:
  elasticsearch-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
        